"""initial commit

Revision ID: 930c63f9dff8
Revises: 
Create Date: 2024-05-15 04:23:09.086696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930c63f9dff8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
